use_frameworks!

target 'SwiftyMenuBar_Example' do
  pod 'SwiftyMenuBar', :path => '../'
  pod 'FontAwesome.swift', '~> 1.6.0'
  pod 'Pastel'

  target 'SwiftyMenuBar_Tests' do
    inherit! :search_paths

    
  end
end
