# references:
# * https://www.objc.io/issues/6-build-tools/travis-ci/
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode10.3
language: swift
# cache: cocoapods
xcode_workspace: Example/SwiftyMenuBar.xcworkspace
xcode_scheme: SwiftyMenuBar-Example
xcode_destination: platform=iOS Simulator,OS=12.4,name=iPhone Xs
podfile: Example/Podfile
before_install:
  - gem install cocoapods
  - pod install --project-directory=Example
script:
#- set -o pipefail && xcodebuild test -enableCodeCoverage YES -workspace Example/SwiftyMenuBar.xcworkspace -scheme SwiftyMenuBar-Example -sdk iphonesimulator9.3 ONLY_ACTIVE_ARCH=NO | xcpretty
- set -o pipefail && xcodebuild -workspace Example/SwiftyMenuBar.xcworkspace -scheme SwiftyMenuBar-Example -destination "platform=iOS Simulator,OS=12.4,name=iPhone Xs" ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint
