os: osx
osx_image: xcode10.3
language: swift
xcode_workspace: SlidingMenuBar.xcworkspace # path to your xcodeproj folder
xcode_scheme: SlidingMenuBar
xcode_destination: platform=iOS Simulator,OS=12.4,name=iPhone Xs
