osx_image: xcode11.3
language: swift
cache: cocoapods

env:
  global:
    - WORKSPACE=Example/SwiftyMenuBar.xcworkspace
    - SCHEME_IOS=SwiftyMenuBar-Example
    - IOS_SDK=iphonesimulator13.2

  matrix:
    - DESTINATION="OS=13.3,name=iPhone 11 Pro" SDK="$IOS_SDK" SCHEME="$SCHEME_IOS" BUILD_EXAMPLE="YES" POD_LINT="YES"
    - DESTINATION="OS=13.0,name=iPhone 11" SDK="$IOS_SDK" SCHEME="$SCHEME_IOS" BUILD_EXAMPLE="YES" POD_LINT="YES"
    - DESTINATION="OS=12.0,name=iPhone XS" SDK="$IOS_SDK" SCHEME="$SCHEME_IOS" BUILD_EXAMPLE="YES" POD_LINT="YES"
    - DESTINATION="OS=11.0,name=iPhone X" SDK="$IOS_SDK" SCHEME="$SCHEME_IOS" BUILD_EXAMPLE="YES" POD_LINT="YES"

    - DESTINATION="OS=13.3,name=iPhone 8 Plus" SDK="$IOS_SDK" SCHEME="$SCHEME_IOS" BUILD_EXAMPLE="YES" POD_LINT="YES"
    - DESTINATION="OS=13.0,name=iPhone 8 Plus" SDK="$IOS_SDK" SCHEME="$SCHEME_IOS" BUILD_EXAMPLE="YES" POD_LINT="YES"
    - DESTINATION="OS=12.0,name=iPhone 7" SDK="$IOS_SDK" SCHEME="$SCHEME_IOS" BUILD_EXAMPLE="YES" POD_LINT="YES"
    - DESTINATION="OS=11.1,name=iPhone 6s" SDK="$IOS_SDK" SCHEME="$SCHEME_IOS" BUILD_EXAMPLE="YES" POD_LINT="YES"

script:
  - set -o pipefail
  - pod install --project-directory=Example
  - if [ $POD_LINT == "YES" ]; then
      pod lib lint;
    fi
  - xcodebuild -workspace "$WORKSPACE" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" ONLY_ACTIVE_ARCH=YES clean test | xcpretty -c
